

GET http://localhost:5279/games

###
GET http://localhost:5279/games/2

###
POST http://localhost:5279/games
Content-Type: application/json

{
    "name": "Minecraft 2",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2014-11-18"
}

###
PUT http://localhost:5279/games/5
Content-Type: application/json

{
    "name": "Minecraft otro",
    "genre": "Kids and Family",
    "price": 9.99,
    "releaseDate": "2014-11-18"
}

###
DELETE http://localhost:5279/games/5 